<facility> ::= [<component> | <subsystem>]

<AddComponent> ::= "add" <component>

<RemoveComponent> ::= "remove" <Number>

ShowFacility ::= "show_facility"

CalculateTotalProduction ::= "calculate_total_production"

CalculateTotalStorage ::= "calculate_total_storage"

<subsystem> ::= "subsystem" "(" component+ ")"

<component> ::= <energy_production_unit> | <storage> | <subsystem>

<energy_production_unit> ::= <energy_production_unit_type> <production>

<energy_production_unit_type> ::= "solar_panel" | "nuclear_plant" | "hydro_plant" | "wind_turbine"

<storage> ::= "storage" "(" <efficiency> "," <max_storage_amount> ")"

<efficiency> ::= <number>

<max_storage_amount> ::= <number>

<production> ::= <number>

<number> ::= digit+

<digit> ::= "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"
